This is a translation of
\href{http://www.gigamonkeys.com/book/beyond-exception-handling-conditions-and-restarts.html}{Beyond
exception handling: conditions and restarts} by Peter Seibel, from Lisp
to R. The original document is copyright (c) 2003-2005, Peter Seibel;
translated with permission.

The majority of the translation involves changing Lisp syntax to R
syntax. There are few differences in the overall system.

\hypertarget{beyond-exception-handling-conditions-and-restarts}{%
\chapter{Beyond Exception Handling: Conditions and
Restarts}\label{beyond-exception-handling-conditions-and-restarts}}

One of R's great features is its \emph{condition} system. It serves a
similar purpose to the exception handling systems in Java, Python, and
C++ but is more flexible. In fact, its flexibility extends beyond error
handling--conditions are more general than exceptions in that a
condition can represent any occurrence during a program's execution that
may be of interest to code at different levels on the call stack. For
example, in the section ``Other Uses for Conditions,'' you'll see that
conditions can be used to emit warnings without disrupting execution of
the code that emits the warning while allowing code higher on the call
stack to control whether the warning message is printed. For the time
being, however, I'll focus on error handling.

The condition system is more flexible than exception systems because
instead of providing a two-part division between the code that signals
an error\textsuperscript{1} and the code that handles
it,\textsuperscript{2} the condition system splits the responsibilities
into three parts--\emph{signaling} a condition, \emph{handling} it, and
\emph{restarting}. In this chapter, I'll describe how you could use
conditions in part of a hypothetical application for analyzing log
files. You'll see how you could use the condition system to allow a
low-level function to detect a problem while parsing a log file and
signal an error, to allow mid-level code to provide several possible
ways of recovering from such an error, and to allow code at the highest
level of the application to define a policy for choosing which recovery
strategy to use.

To start, I'll introduce some terminology: \emph{errors}, as I'll use
the term, are the consequences of Murphy's law. If something can go
wrong, it will: a file that your program needs to read will be missing,
a disk that you need to write to will be full, the server you're talking
to will crash, or the network will go down. If any of these things
happen, it may stop a piece of code from doing what you want. But
there's no bug; there's no place in the code that you can fix to make
the nonexistent file exist or the disk not be full. However, if the rest
of the program is depending on the actions that were going to be taken,
then you'd better deal with the error somehow or you \emph{will} have
introduced a bug. So, errors aren't caused by bugs, but neglecting to
handle an error is almost certainly a bug.

So, what does it mean to handle an error? In a well-written program,
each function is a black box hiding its inner workings. Programs are
then built out of layers of functions: high-level functions are built on
top of the lower-level functions, and so on. This hierarchy of
functionality manifests itself at runtime in the form of the call stack:
if \texttt{high} calls \texttt{medium}, which calls \texttt{low}, when
the flow of control is in \texttt{low}, it's also still in
\texttt{medium} and \texttt{high}, that is, they're still on the call
stack.

Because each function is a black box, function boundaries are an
excellent place to deal with errors. Each function--\texttt{low}, for
example--has a job to do. Its direct caller--\texttt{medium} in this
case--is counting on it to do its job. However, an error that prevents
it from doing its job puts all its callers at risk: \texttt{medium}
called \texttt{low} because it needs the work done that \texttt{low}
does; if that work doesn't get done, \texttt{medium} is in trouble. But
this means that \texttt{medium}'s caller, \texttt{high}, is also in
trouble--and so on up the call stack to the very top of the program. On
the other hand, because each function is a black box, if any of the
functions in the call stack can somehow do their job despite underlying
errors, then none of the functions above it needs to know there was a
problem--all those functions care about is that the function they called
somehow did the work expected of it.

In most languages, errors are handled by returning from a failing
function and giving the caller the choice of either recovering or
failing itself. Some languages use the normal function return mechanism,
while languages with exceptions return control by \emph{throwing} or
\emph{raising} an exception. Exceptions are a vast improvement over
using normal function returns, but both schemes suffer from a common
flaw: while searching for a function that can recover, the stack
unwinds, which means code that might recover has to do so without the
context of what the lower-level code was trying to do when the error
actually occurred.

Consider the hypothetical call chain of \texttt{high}, \texttt{medium},
\texttt{low}. If \texttt{low} fails and \texttt{medium} can't recover,
the ball is in \texttt{high}'s court. For \texttt{high} to handle the
error, it must either do its job without any help from \texttt{medium}
or somehow change things so calling \texttt{medium} will work and call
it again. The first option is theoretically clean but implies a lot of
extra code--a whole extra implementation of whatever it was
\texttt{medium} was supposed to do. And the further the stack unwinds,
the more work that needs to be redone. The second option--patching
things up and retrying--is tricky; for \texttt{high} to be able to
change the state of the world so a second call into \texttt{medium}
won't end up causing an error in \texttt{low}, it'd need an unseemly
knowledge of the inner workings of both \texttt{medium} and
\texttt{low}, contrary to the notion that each function is a black box.

\hypertarget{the-r-way}{%
\section{The R Way}\label{the-r-way}}

R's error handling system gives you a way out of this conundrum by
letting you separate the code that actually recovers from an error from
the code that decides how to recover. Thus, you can put recovery code in
low-level functions without committing to actually using any particular
recovery strategy, leaving that decision to code in high-level
functions.

To get a sense of how this works, let's suppose you're writing an
application that reads some sort of textual log file, such as a Web
server's log. Somewhere in your application you'll have a function to
parse the individual log entries. Let's assume you'll write a function,
\texttt{parse\_log\_entry()}, that will be passed a string containing
the text of a single log entry and that is supposed to return a
\texttt{log\_entry()} object representing the entry. This function will
be called from a function, \texttt{parse\_log\_file()}, that reads a
complete log file and returns a list of objects representing all the
entries in the file.

To keep things simple, the \texttt{parse\_log\_entry()} function will
not be required to parse incorrectly formatted entries. It will,
however, be able to detect when its input is malformed. But what should
it do when it detects bad input? In C you'd return a special value to
indicate there was a problem. In Java or Python you'd throw or raise an
exception. In R, you signal a condition.

\hypertarget{conditions}{%
\section{Conditions}\label{conditions}}

A \emph{condition} is an S3 object whose class indicates the general
nature of the condition and whose instance data carries information
about the details of the particular circumstances that lead to the
condition being signaled.\textsuperscript{3} In this hypothetical log
analysis program, you might define a condition class,
\texttt{malformed\_log\_entry\_error}, that \texttt{parse\_log\_entry()}
will signal if it's given data it can't parse.

Conditional classes are regular S3 classes, built up from a list with
components \texttt{message} and \texttt{call}. There is no built in
function to generate a new object of class condition, but we can add
one:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{condition <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(subclass, message, }\DataTypeTok{call =} \KeywordTok{sys.call}\NormalTok{(}\OperatorTok{-}\DecValTok{1}\NormalTok{), ...) \{}
  \KeywordTok{structure}\NormalTok{(}
    \DataTypeTok{class =} \KeywordTok{c}\NormalTok{(subclass, }\StringTok{"condition"}\NormalTok{),}
    \KeywordTok{list}\NormalTok{(}\DataTypeTok{message =}\NormalTok{ message, }\DataTypeTok{call =}\NormalTok{ call, ...)}
\NormalTok{  )}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

When using the condition system for error handling, you should define
your conditions as subclasses of \texttt{error}, a subclass of
\texttt{condition}. Thus, you might define
\texttt{malformed\_log\_entry\_error}, with a slot to hold the argument
that was passed to \texttt{parse\_log\_entry()}, like this:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{malformed_log_entry_error <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(text) \{}
\NormalTok{  msg <-}\StringTok{ }\KeywordTok{paste0}\NormalTok{(}\StringTok{"Malformed log entry: "}\NormalTok{, text)}
  \KeywordTok{condition}\NormalTok{(}\KeywordTok{c}\NormalTok{(}\StringTok{"malformed_log_entry_error"}\NormalTok{, }\StringTok{"error"}\NormalTok{),}
    \DataTypeTok{message =}\NormalTok{ msg, }
    \DataTypeTok{text =}\NormalTok{ text}
\NormalTok{  )}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\hypertarget{condition-handlers}{%
\section{Condition Handlers}\label{condition-handlers}}

In \texttt{parse\_log\_entry()} you'll signal a
\texttt{malformed\_log\_entry\_error} if you can't parse the log entry.
You signal errors with the function \texttt{stop()}. \texttt{stop()} is
normally just called with a string, the error message, but you can also
call it with a condition object. Thus, you could write
\texttt{parse\_log\_entry()} like this, eliding the details of actually
parsing a log entry:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{parse_log_entry <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(text) \{}
  \ControlFlowTok{if}\NormalTok{ (}\OperatorTok{!}\KeywordTok{well_formed_log_entry}\NormalTok{(text)) \{}
    \KeywordTok{stop}\NormalTok{(}\KeywordTok{malformed_log_entry_error}\NormalTok{(text))}
\NormalTok{  \}}
  
  \KeywordTok{new_log_entry}\NormalTok{(text)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

What happens when the error is signaled depends on the code above
\texttt{parse\_log\_entry()} on the call stack. To avoid a top level
error message, you must establish a \emph{condition handler} in one of
the functions leading to the call to \texttt{parse\_log\_entry}. When a
condition is signaled, the signaling machinery looks through a list of
active condition handlers, looking for a handler that can handle the
condition being signaled based on the condition's class. Each condition
handler consists of a type specifier indicating what types of conditions
it can handle and a function that takes a single argument, the
condition. At any given moment there can be many active condition
handlers established at various levels of the call stack. When a
condition is signaled, the signaling machinery finds the most recently
established handler whose type specifier is compatible with the
condition being signaled and calls its function, passing it the
condition object.

The handler function can then choose whether to handle the condition.
The function can decline to handle the condition by simply returning
normally, in which case control returns to next most recently
established handler with a compatible type specifier. To handle the
condition, the function must transfer control out of the signaller via a
\emph{nonlocal exit}. In the next section, you'll see how a handler can
choose where to transfer control. However, many condition handlers
simply want to unwind the stack to the place where they were established
and then run some code. The function \texttt{tryCatch()} establishes
this kind of condition handler. The basic form of a \texttt{tryCatch} is
as follows:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{tryCatch}\NormalTok{(expression, }
  \DataTypeTok{condition_class_1 =} \ControlFlowTok{function}\NormalTok{(var) ...,}
  \DataTypeTok{condition_class_2 =} \ControlFlowTok{function}\NormalTok{(var) ...,}
\NormalTok{  ...}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

If the \emph{expression} returns normally, then its value is returned by
the \texttt{tryCatch()}. The body of a \texttt{tryCatch()} must be a
single expression; but you can always use \texttt{\{} to combine several
expressions into a single form. If, however, the expression signals a
condition that's an instance of any of the \emph{condition class}s then
the code in the appropriate error clause is executed and its value
returned by the \texttt{tryCatch()}. The \emph{var} is the name of the
variable that will hold the condition object when the handler code is
executed. If the code doesn't need to access the condition object, you
can omit the variable name.

For instance, one way to handle the
\texttt{malformed\_log\_entry\_error} signaled by
\texttt{parse\_log\_entry()} in its caller, \texttt{parse\_log\_file()},
would be to skip the malformed entry. In the following function, the
\texttt{tryCatch()} expression will either return the value returned by
\texttt{parse\_log\_entry()} or return \texttt{NULL} if a
\texttt{malformed\_log\_entry\_error} is signaled.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{parse_log_file <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(file) \{}
\NormalTok{  lines <-}\StringTok{ }\KeywordTok{readLines}\NormalTok{(file)}
  
  \KeywordTok{lapply}\NormalTok{(lines, }\ControlFlowTok{function}\NormalTok{(text) \{}
    \KeywordTok{tryCatch}\NormalTok{(}
      \DataTypeTok{malformed_log_entry_error =} \ControlFlowTok{function}\NormalTok{(e) }\OtherTok{NULL}\NormalTok{,}
      \KeywordTok{parse_log_entry}\NormalTok{(text)}
\NormalTok{    )}
\NormalTok{  \})}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

When \texttt{parse\_log\_entry()} returns normally, its value will be
collected by the \texttt{lapply()}. But if \texttt{parse\_log\_entry}
signals a \texttt{malformed\_log\_entry\_error}, then the error clause
will return \texttt{NULL}.

This version of \texttt{parse\_log\_file()} has one serious deficiency:
it's doing too much. As its name suggests, the job of
\texttt{parse\_log\_file()} is to parse the file and produce a list of
\texttt{log\_entry} objects; if it can't, it's not its place to decide
what to do instead. What if you want to use \texttt{parse\_log\_file()}
in an application that wants to tell the user that the log file is
corrupted or one that wants to recover from malformed entries by fixing
them up and re-parsing them? Or maybe an application is fine with
skipping them but only until a certain number of corrupted entries have
been seen.

You could try to fix this problem by moving the \texttt{tryCatch()} to a
higher-level function. However, then you'd have no way to implement the
current policy of skipping individual entries--when the error was
signaled, the stack would be unwound all the way to the higher-level
function, abandoning the parsing of the log file altogether. What you
want is a way to provide the current recovery strategy without requiring
that it always be used.

\hypertarget{java-style-exception-handling}{%
\subsection{Java style exception
handling}\label{java-style-exception-handling}}

\texttt{tryCatch} is the nearest analog in R to Java- or Python-style
exception handling. Where you might write this in Java:

\begin{verbatim}
try {
  doStuff();
  doMoreStuff();
} catch (SomeException se) {
  recover(se);
}
\end{verbatim}

or this in Python:

\begin{verbatim}
try:
  doStuff()
  doMoreStuff()
except SomeException, se:
  recover(se)
\end{verbatim}

in R you'd write this:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{tryCatch}\NormalTok{(\{}
  \KeywordTok{doStuff}\NormalTok{()}
  \KeywordTok{doMoreStuff}\NormalTok{()}
\NormalTok{\}, }\DataTypeTok{some_exception =} \ControlFlowTok{function}\NormalTok{(se) \{}
  \KeywordTok{recover}\NormalTok{(se)}
\NormalTok{\})}
\end{Highlighting}
\end{Shaded}

\hypertarget{restarts}{%
\section{Restarts}\label{restarts}}

The condition system lets you do this by splitting the error handling
code into two parts. You place code that actually recovers from errors
into \emph{restarts}, and condition handlers can then handle a condition
by invoking an appropriate restart. You can place restart code in mid-
or low-level functions, such as \texttt{parse\_log\_file()} or
\texttt{parse\_log\_entry()}, while moving the condition handlers into
the upper levels of the application.

To change \texttt{parse\_log\_file()} so it establishes a restart
instead of a condition handler, you can change the \texttt{tryCatch()}
to a \texttt{withRestarts()}. The form of \texttt{withRestarts} is very
similar to a \texttt{tryCatch()}. In general, a restart name should
describe the action the restart takes. In \texttt{parse\_log\_file()},
you can call the restart \texttt{skip\_log\_entry} since that's what it
does. The new version will look like this:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{parse_log_file <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(file) \{}
\NormalTok{  lines <-}\StringTok{ }\KeywordTok{readLines}\NormalTok{(file)}
  
  \KeywordTok{lapply}\NormalTok{(lines, }\ControlFlowTok{function}\NormalTok{(text) \{}
    \KeywordTok{withRestarts}\NormalTok{(}
      \KeywordTok{parse_log_entry}\NormalTok{(text),}
      \DataTypeTok{skip_log_entry =} \ControlFlowTok{function}\NormalTok{(e) }\OtherTok{NULL}
\NormalTok{    )}
\NormalTok{  \})}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

If you invoke this version of \texttt{parse\_log\_file()} on a log file
containing corrupted entries, it won't handle the error directly; you'll
end up in the debugger. However, there among the various restarts listed
by \texttt{findRestarts()} will be one called \texttt{skip\_log\_entry},
which, if you choose it, will cause \texttt{parse\_log\_file()} to
continue on its way as before. To avoid ending up in the debugger, you
can establish a condition handler that invokes the
\texttt{skip\_log\_entry} restart automatically.

The advantage of establishing a restart rather than having
\texttt{parse\_log\_file()} handle the error directly is it makes
\texttt{parse\_log\_file()} usable in more situations. The higher-level
code that invokes \texttt{parse\_log\_file()} doesn't have to invoke the
\texttt{skip\_log\_entry} restart. It can choose to handle the error at
a higher level. Or, as I'll show in the next section, you can add
restarts to \texttt{parse\_log\_entry()} to provide other recovery
strategies, and then condition handlers can choose which strategy they
want to use.

But before I can talk about that, you need to see how to set up a
condition handler that will invoke the \texttt{skip\_log\_entry}
restart. You can set up the handler anywhere in the chain of calls
leading to \texttt{parse\_log\_file()}. This may be quite high up in
your application, not necessarily in \texttt{parse\_log\_file()}'s
direct caller. For instance, suppose the main entry point to your
application is a function, \texttt{log\_analyzer()}, that finds a bunch
of logs and analyzes them with the function \texttt{analyze\_log()},
which eventually leads to a call to \texttt{parse\_log\_file()}. Without
any error handling, it might look like this:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{log_analyzer <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{() \{}
\NormalTok{  logs <-}\StringTok{ }\KeywordTok{find_all_logs}\NormalTok{()}
  \KeywordTok{lapply}\NormalTok{(logs, analyze_log)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

The job of \texttt{analyze\_log()} is to call, directly or indirectly,
\texttt{parse\_log\_file()} and then do something with the list of log
entries returned. An extremely simple version might look like this:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{analyze_log <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(log) \{}
\NormalTok{  entries <-}\StringTok{ }\KeywordTok{parse_log_file}\NormalTok{(log)}
  \KeywordTok{lapply}\NormalTok{(entries, analyze_entry)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

where the function \texttt{analyze\_entry()} is presumably responsible
for extracting whatever information you care about from each log entry
and stashing it away somewhere.

Assuming you always want to skip malformed log entries, you could change
this function to establish a condition handler that invokes the
\texttt{skip\_log\_entry} restart for you. However, you can't use
\texttt{tryCatch()} to establish the condition handler because then the
stack would be unwound to the function where the \texttt{tryCatch()}
appears. Instead, you need to use the lower-level macro
\texttt{withCallingHandlers()}. The basic form of
\texttt{withCallingHandlers()} is as follows:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{withCallingHandlers}\NormalTok{(}
\NormalTok{  expr,}
  \DataTypeTok{condition_1 =} \ControlFlowTok{function}\NormalTok{() ...,}
  \DataTypeTok{condition_2 =} \ControlFlowTok{function}\NormalTok{() ....}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

An important difference between \texttt{tryCatch()} and
\texttt{withCallingHandlers()} is that the handler function bound by
\texttt{withCallingHandlers()} will be run without unwinding the
stack--the flow of control will still be in the call to
\texttt{parse\_log\_entry()} when this function is called. A call to
\texttt{invokeRestart()} will find and invoke the most recently bound
restart with the given name. So you can add a handler to
\texttt{log\_analyzer()} that will invoke the \texttt{skip\_log\_entry}
restart established in \texttt{parse\_log\_file()} like
this:\textsuperscript{5}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{log_analyzer <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{() \{}
\NormalTok{  logs <-}\StringTok{ }\KeywordTok{find_all_logs}\NormalTok{()}
  
  \KeywordTok{withCallingHandlers}\NormalTok{(}
    \DataTypeTok{malformed_log_entry_error =} \ControlFlowTok{function}\NormalTok{(e) }\KeywordTok{invokeRestart}\NormalTok{(}\StringTok{"skip_log_entry"}\NormalTok{),}
    \KeywordTok{lapply}\NormalTok{(logs, analyze_log)}
\NormalTok{  )}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

In this \texttt{withCallingHandlers()}, the handler function is an
anonymous function that invokes the restart \texttt{skip\_log\_entry}.
You could also define a named function that does the same thing and bind
it instead. In fact, a common practice when defining a restart is to
define a function, with the same name and taking a single argument, the
condition, that invokes the eponymous restart. Such functions are called
\emph{restart functions}. You could define a restart function for
\texttt{skip\_log\_entry} like this:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{skip_log_entry <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{() }\KeywordTok{invokeRestart}\NormalTok{(}\StringTok{"skip_log_entry"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Then you could change the definition of \texttt{log\_analyzer()} to
this:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{log_analyzer <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{() \{}
\NormalTok{  logs <-}\StringTok{ }\KeywordTok{find_all_logs}\NormalTok{()}
  
  \KeywordTok{withCallingHandlers}\NormalTok{(}
    \DataTypeTok{malformed_log_entry_error =}\NormalTok{ skip_log_entry,}
    \KeywordTok{lapply}\NormalTok{(logs, analyze_log)}
\NormalTok{  )}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

As written, the \texttt{skip\_log\_entry} restart function assumes that
a \texttt{skip\_log\_entry} restart has been established. If a
\texttt{malformed\_log\_entry\_error} is ever signaled by code called
from \texttt{log\_analyzer()} without a \texttt{skip\_log\_entry} having
been established, the call to \texttt{invokeRestart()} will signal an
error when it fails to find the \texttt{skip\_log\_entry} restart. If
you want to allow for the possibility that a
\texttt{malformed\_log\_entry\_error} might be signaled from code that
doesn't have a \texttt{skip\_log\_entry} restart established, you could
change the \texttt{skip\_log\_entry} function to this:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{skip_log_entry <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{() \{}
\NormalTok{  r <-}\StringTok{ }\KeywordTok{findRestart}\NormalTok{(}\StringTok{"skip_log_entry"}\NormalTok{) }
  \ControlFlowTok{if}\NormalTok{ (}\KeywordTok{is.null}\NormalTok{(r)) }\KeywordTok{return}\NormalTok{()}
  
  \KeywordTok{invokeRestart}\NormalTok{(r)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\texttt{findRestart} looks for a restart with a given name and returns
an object representing the restart if the restart is found and
\texttt{NULL} if not. You can invoke the restart by passing the restart
object to \texttt{invokeRestart()}. Thus, when \texttt{skip\_log\_entry}
is bound with \texttt{withCallingHandlers()}, it will handle the
condition by invoking the \texttt{skip\_log\_entry} restart if one is
available and otherwise will return normally, giving other condition
handlers, bound higher on the stack, a chance to handle the condition.

\hypertarget{providing-multiple-restarts}{%
\section{Providing Multiple
Restarts}\label{providing-multiple-restarts}}

Since restarts must be explicitly invoked to have any effect, you can
define multiple restarts, each providing a different recovery strategy.
As I mentioned earlier, not all log-parsing applications will
necessarily want to skip malformed entries. Some applications might want
\texttt{parse\_log\_file()} to include a special kind of object
representing malformed entries in the list of \texttt{log-entry}
objects; other applications may have some way to repair a malformed
entry and may want a way to pass the fixed entry back to
\texttt{parse\_log\_entry()}.

To allow more complex recovery protocols, restarts can take arbitrary
arguments, which are passed in the call to \texttt{invokeRestart()}. You
can provide support for both the recovery strategies I just mentioned by
adding two restarts to \texttt{parse\_log\_entry()}, each of which takes
a single argument. One simply returns the value it's passed as the
return value of \texttt{parse\_log\_entry()}, while the other tries to
parse its argument in the place of the original log entry.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{parse_log_entry <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(text) \{}
  \ControlFlowTok{if}\NormalTok{ (}\KeywordTok{well_formed_log_entry}\NormalTok{(text)) \{}
    \KeywordTok{return}\NormalTok{(}\KeywordTok{new_log_entry}\NormalTok{(text))}
\NormalTok{  \}}
  
  \KeywordTok{withRestarts}\NormalTok{(}
    \KeywordTok{stop}\NormalTok{(}\KeywordTok{malformed_log_entry_error}\NormalTok{(text)),}
    \DataTypeTok{use_value =} \ControlFlowTok{function}\NormalTok{(x) x,}
    \DataTypeTok{reparse_entry =} \ControlFlowTok{function}\NormalTok{(fixed_text) }\KeywordTok{parse_log_entry}\NormalTok{(fixed_text)}
\NormalTok{  )}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

The name \texttt{use\_value()} is a standard name for this kind of
restart. You can define a restart function for \texttt{use\_value}
similar to the \texttt{skip\_log\_entry} function you just defined.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{use_value <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(x) }\KeywordTok{invokeRestart}\NormalTok{(}\StringTok{"use_value"}\NormalTok{, x)}
\end{Highlighting}
\end{Shaded}

So, if you wanted to change the policy on malformed entries to one that
created an instance of \texttt{malformed\_log\_entry}, you could change
\texttt{log\_analyzer()} to this (assuming the existence of a
\texttt{malformed\_log\_entry} constructor with a \texttt{text}
parameter):

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{log_analyzer <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{() \{}
\NormalTok{  logs <-}\StringTok{ }\KeywordTok{find_all_logs}\NormalTok{()}
  
  \KeywordTok{withCallingHandlers}\NormalTok{(}
    \DataTypeTok{malformed_log_entry_error =} \ControlFlowTok{function}\NormalTok{(text) \{}
      \KeywordTok{use_value}\NormalTok{(}\KeywordTok{malformed_log_entry}\NormalTok{(text))}
\NormalTok{    \},}
    \KeywordTok{lapply}\NormalTok{(logs, analyze_log)}
\NormalTok{  )}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

You could also have put these new restarts into
\texttt{parse\_log\_file()} instead of \texttt{parse\_log\_entry()}.
However, you generally want to put restarts in the lowest-level code
possible. It wouldn't, though, be appropriate to move the
\texttt{skip\_log\_entry} restart into \texttt{parse\_log\_entry()}
since that would cause \texttt{parse\_log\_entry()} to sometimes return
normally with \texttt{NULL}, the very thing you started out trying to
avoid. And it'd be an equally bad idea to remove the
\texttt{skip\_log\_entry} restart on the theory that the condition
handler could get the same effect by invoking the \texttt{use-value}
restart with \texttt{NULL} as the argument; that would require the
condition handler to have intimate knowledge of how the
\texttt{parse\_log\_file()} works. As it stands, the
\texttt{skip\_log\_entry} is a properly abstracted part of the
log-parsing API.

\hypertarget{other-uses-for-conditions}{%
\section{Other Uses for Conditions}\label{other-uses-for-conditions}}

While conditions are mainly used for error handling, they can be used
for other purposes--you can use conditions, condition handlers, and
restarts to build a variety of protocols between low- and high-level
code. The key to understanding the potential of conditions is to
understand that merely signaling a condition has no effect on the flow
of control.

The primitive signaling function \texttt{signalCondition()} implements
the mechanism of searching for an applicable condition handler and
invoking its handler function. The reason a handler can decline to
handle a condition by returning normally is because the call to the
handler function is just a regular function call--when the handler
returns, control passes back to \texttt{signalCondition()}, which then
looks for another, less recently bound handler that can handle the
condition. If \texttt{signalCondition()} runs out of condition handlers
before the condition is handled, it also returns normally.

The \texttt{stop()} function you've been using calls
\texttt{signalCondition()}. If the error is handled by a condition
handler that transfers control via \texttt{tryCatch()} or by invoking a
restart, then the call to \texttt{signalCondition()} never returns.

Another condition signaling function, \texttt{warning()}, provides an
example of a different kind of protocol built on the condition system.
Like \texttt{stop()}, \texttt{warnings()} calls
\texttt{signalCondition()} to signal a condition. But if
\texttt{signalCondition()} returns, \texttt{warning()} doesn't throw a
top-level error--it prints the condition to \texttt{stderr} and returns
\texttt{NULL}, allowing its caller to proceed. \texttt{warning()} also
establishes a restart, \texttt{muffle\_warning()}, around the call to
\texttt{signalCondition()} that can be used by a condition handler to
make \texttt{warning()} return without printing anything. Of course, a
condition signaled with \texttt{warning()} could also be handled in some
other way--a condition handler could ``promote'' a warning to an error
by handling it as if it were an error.

For instance, in the log-parsing application, if there were ways a log
entry could be slightly malformed but still parsable, you could write
\texttt{parse\_log\_entry()} to go ahead and parse the slightly
defective entries but to signal a condition with \texttt{warning()} when
it did. Then the larger application could choose to let the warning
print, to muffle the warning, or to treat the warning like an error,
recovering the same way it would from a
\texttt{malformed\_log\_entry\_error}.

You can also build your own protocols on
\texttt{signalCondition()}--whenever low-level code needs to communicate
information back up the call stack to higher-level code, the condition
mechanism is a reasonable mechanism to use. But for most purposes, one
of the standard error or warning protocols should suffice.

Unfortunately, it's the fate of error handling to always get short
shrift in programming texts--proper error handling, or lack thereof, is
often the biggest difference between illustrative code and hardened,
production-quality code. The trick to writing the latter has more to do
with adopting a particularly rigorous way of thinking about software
than with the details of any particular programming language constructs.
That said, if your goal is to write that kind of software, you'll find
the R condition system is an excellent tool for writing robust code and
one that fits quite nicely into R's incremental development style.

\hypertarget{writing-robust-software}{%
\subsection{Writing Robust Software}\label{writing-robust-software}}

For information on writing robust software, you could do worse than to
start by finding a copy of \emph{Software Reliability} (John Wiley \&
Sons, 1976) by Glenford J. Meyers. Bertrand Meyer's writings on Design
By Contract also provide a useful way of thinking about software
correctness. For instance, see Chapters 11 and 12 of his
\emph{Object-Oriented Software Construction} (Prentice Hall, 1997). Keep
in mind, however, that Bertrand Meyer is the inventor of Eiffel, a
statically typed bondage and discipline language in the Algol/Ada
school. While he has a lot of smart things to say about object
orientation and software reliability, there's a fairly wide gap between
his view of programming and The R Way. Finally, for an excellent
overview of the larger issues surrounding building fault-tolerant
systems, see Chapter 3 of the classic \emph{Transaction Processing:
Concepts and Techniques} (Morgan Kaufmann, 1993) by Jim Gray and Andreas
Reuter.

\textsuperscript{1}\emph{Throws} or \emph{raises} an exception in
Java/Python terms

\textsuperscript{2}\emph{Catches} the exception in Java/Python terms

\textsuperscript{3}In this respect, a condition is a lot like an
exception in Java or Python except not all conditions represent an error
or \emph{exceptional} situation.

\textsuperscript{5}The compiler may complain if the parameter is never
used. You can silence that warning by adding a declaration
\texttt{(declare\ (ignore\ c))} as the first expression in the
\texttt{LAMBDA} body.
